"use client";
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { Activity, ArrowLeft, Camera, Check, ChevronLeft, ChevronRight, Columns2, Download, ExternalLink, FlipHorizontal2, Layers2, Pause, Play, Repeat2, RotateCcw, Settings2, SkipBack, SkipForward, SlidersHorizontal, Square, Upload, X } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { useStudio } from '@/lib/use-studio';
import {RecentMediaPicker} from '@/components/recent-media';
import {rememberLink,historyError} from '@/lib/recent-media';
import {YouTubeReference} from '@/components/youtube-reference';
import {parseYouTubeLink} from '@/lib/youtube';
import { TempoConfig } from '@/components/tempo-config';
import { VideoTracks } from '@/components/video-tracks';
import {AlignmentEditor} from '@/components/alignment-editor';
import { PoseOverlay } from '@/components/pose-overlay';
import { detectPoses } from '@/lib/pose-detector';
import { alignmentCss, perspectivePose, alignPoses, displayPose, transformPose, jointAngle, type Point, type Size } from '@/lib/pose-geometry';
import { beatAt, clamp, mapSelfTime, phraseLoop, synchronizedRate, timeLabel } from '@/lib/rhythm';
import { registerStudioTools, type ModelContext } from '@/lib/webmcp';
import {BackgroundVideo} from '@/components/background-video';
import {BackgroundControls} from '@/components/background-controls';
import {defaultBackground,restoreBackground,type BackgroundSettings} from '@/lib/background';

type ConfigStep='origin'|'tempo'|'display'|'source';
function Numeric({label,value,onChange,min=0,max=999,step=.1,disabled=false}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number;disabled?:boolean}){
 const [text,setText]=useState(String(value));useEffect(()=>setText(String(Math.round(value*1000)/1000)),[value]);
 const commit=()=>{const n=Number(text);if(text.trim()&&Number.isFinite(n)){const v=clamp(n,min,max);onChange(v);setText(String(v));}else setText(String(value));};
 return <label className="numeric"><span>{label}</span><input type="number" inputMode="decimal" min={min} max={max} step={step} value={text} disabled={disabled} onChange={e=>setText(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}} aria-label={label}/></label>;
}
function Range({label,value,min=0,max,step=.01,onChange,disabled=false}:{label:string;value:number;min?:number;max:number;step?:number;onChange:(n:number)=>void;disabled?:boolean}){return <Slider aria-label={label} value={[value]} min={min} max={Math.max(max,min+.001)} step={step} disabled={disabled} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/>;}

export default function Home(){
 const s=useStudio();const [mode,setMode]=useState('compare'),[config,setConfig]=useState<number|null>(null),[step,setStep]=useState<ConfigStep>('origin');
 const [panel,setPanel]=useState<'speed'|'loop'|'alignment'|'tracks'|null>(null),[phrases,setPhrases]=useState(1),[drag,setDrag]=useState<number|null>(null);
 const [link,setLink]=useState(''),[savedLink,setSavedLink]=useState('');
 const [backgrounds,setBackgrounds]=useState<BackgroundSettings[]>([{...defaultBackground},{...defaultBackground}]),[backgroundReady,setBackgroundReady]=useState(['','']);
 const backgroundKeys=[s.sources[0]?.key||'empty',s.camera?'camera':s.sources[1]?.key||'empty'];
 useEffect(()=>{setBackgroundReady(['','']);setBackgrounds(backgroundKeys.map(key=>{try{return restoreBackground(JSON.parse(localStorage.getItem('wotagei:background:'+key)||'null'));}catch{return {...defaultBackground};}}));},[backgroundKeys[0],backgroundKeys[1]]);
 function changeBackground(index:number,value:BackgroundSettings){setBackgrounds(v=>v.map((old,i)=>i===index?value:old));if(value.mode!==backgrounds[index].mode)setBackgroundReady(v=>v.map((old,i)=>i===index?'':old));try{localStorage.setItem('wotagei:background:'+backgroundKeys[index],JSON.stringify(value));}catch{s.setNotice('背景の設定を端末に保存できませんでした。この画面では利用できます。');}}
 const [poseBusy,setPoseBusy]=useState(false),[poses,setPoses]=useState<{points:Point[][];stage:Size;times:number[];mirrors:boolean[]}|null>(null);
 const poseRequest=useRef(0),selfStage=useRef<HTMLDivElement>(null);
 const [stageSize,setStageSize]=useState<Size>({width:0,height:0});
 useEffect(()=>{const el=selfStage.current;if(!el)return;const observer=new ResizeObserver(entries=>{const rect=entries[0]?.contentRect;if(!rect)return;setStageSize(old=>old.width===rect.width&&old.height===rect.height?old:{width:rect.width,height:rect.height});});observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{poseRequest.current++;setPoseBusy(false);setPoses(null);},[stageSize.width,stageSize.height]);
 useEffect(()=>{poseRequest.current++;setPoseBusy(false);setPoses(null);},[s.sources[0]?.key,s.sources[1]?.key,s.mirrors[0],s.mirrors[1],s.camera]);
 useEffect(()=>()=>{poseRequest.current++;},[]);
 const studioRef=useRef(s);useEffect(()=>{studioRef.current=s;});
 useEffect(()=>{try{const l=localStorage.getItem('wotagei:reference-link');if(l&&/^https:\/\//.test(l))setSavedLink(l);}catch{}
  const context=(document as Document & {modelContext?:ModelContext}).modelContext;if(!context)return;
  return registerStudioTools(context,()=>{const v=studioRef.current;return{bpm:v.bpm.map((n,i)=>v.bpmKinds[i]==='unset'?null:n),bpmKinds:v.bpmKinds,origins:v.origins,rate:v.rate,time:v.time,playing:v.playing,loaded:v.sources.map(Boolean),loop:v.loop};},input=>flushSync(()=>{const v=studioRef.current;v.pause();if(input.referenceBpm!==undefined)v.applyBpm(0,input.referenceBpm!,'manual');if(input.selfBpm!==undefined)v.applyBpm(1,input.selfBpm!,'manual');if(input.rate!==undefined)v.setRate(input.rate);}));
 },[]);
 useEffect(()=>{if(!s.notice)return;const timer=setTimeout(()=>s.setNotice(''),7000);return()=>clearTimeout(timer);},[s.notice]);
 const isYoutube=!!s.sources[0]?.youtube;
 const hasReference=isYoutube?s.youtubeReady:!!s.sources[0]&&s.durations[0]>0,beat=beatAt(s.time,s.origins[0],s.bpm[0]);
 const selfRate=synchronizedRate(s.rate,s.bpm[0],s.bpm[1]),invalidRate=!!s.sources[1]&&!s.camera&&(selfRate<.25||selfRate>4);
 const targetSelf=mapSelfTime(s.time,s.origins[0],s.origins[1],s.bpm[0],s.bpm[1]);
 const missingBpm=s.bpmKinds[0]==='unset'?0:s.sources[1]&&!s.camera&&s.bpmKinds[1]==='unset'?1:null;
 const counted=hasReference&&s.bpmKinds[0]!=='unset';
 const overlay=mode==='overlay'&&config===null&&!isYoutube;
 function openConfig(index:number,tab?:ConfigStep){setPanel(null);s.pause();s.setNotice('');setStep(tab||(s.sources[index]&&!(index===1&&s.camera)?'tempo':'source'));setConfig(index);}
 function closeConfig(save=false){s.pause();if(save)s.saveSettings();setConfig(null);}
 function changeStep(value:string){s.pause();s.setNotice('');setStep(value as ConfigStep);}
 function setLoopFromPhrase(count:number){const bounds=phraseLoop(s.time,s.origins[0],s.bpm[0],count,s.durations[0]);if(bounds.end-bounds.start<.1){s.setNotice('少し前に戻して、ループする区間を選んでください。');return;}setPhrases(count);s.setLoop({...bounds,enabled:true});s.seek(bounds.start);}
 function saveLink(value=link){try{
  const url=new URL(value.trim());
  if(['x.com','www.x.com','twitter.com','www.twitter.com'].includes(url.hostname)&&url.protocol==='https:'){
   void rememberLink(url.href,'link').catch(e=>s.setNotice(historyError(e)));setSavedLink(url.href);localStorage.setItem('wotagei:reference-link',url.href);setLink('');s.setNotice('Xは元サイトで開ける参考リンクとして保存しました。');return;
  }
  const youtube=parseYouTubeLink(value);s.loadYoutube(youtube);setMode('compare');setConfig(null);setPanel(null);setSavedLink(youtube.url);setLink('');
  try{localStorage.setItem('wotagei:reference-link',youtube.url);}catch{}
 }catch(e){s.setNotice(e instanceof TypeError?'YouTubeの共有リンクを https:// から貼ってください。':e instanceof Error?e.message:'YouTubeの動画リンクを貼ってください。');}}
 async function autoAlign(){if(isYoutube){s.setNotice('骨格合わせにはお手本の動画ファイルを選んでください。');return;}s.pause();const r=s.reference.current,v=s.self.current;if(!r||!v||!s.sources[0]||(!s.sources[1]&&!s.camera)){s.setNotice('2本の動画を読み込み、最初の仁王立ちの場面で止めてください。');return;}const id=++poseRequest.current;setPoseBusy(true);s.setNotice('骨格を読み取り中です。初回はモデルを読み込みます。');const stage={width:r.parentElement!.clientWidth,height:r.parentElement!.clientHeight},times=[r.currentTime,v.currentTime];try{const raw=await detectPoses([r,v]);if(id!==poseRequest.current)return;const points=raw.map((p,i)=>displayPose(p,{width:i===0?r.videoWidth:v.videoWidth,height:i===0?r.videoHeight:v.videoHeight},stage,s.mirrors[i]));const fitted=alignPoses(points[0],perspectivePose(points[1],s.alignment,stage),stage,s.alignment.rotation);s.setAlignment(a=>({...a,...fitted}));setPoses({points,stage,times,mirrors:[...s.mirrors]});s.setNotice('頭・腰・両足から位置と大きさを合わせました。傾き・遠近・足の開きは自動変更しません。');}catch(e){if(id===poseRequest.current)s.setNotice(e instanceof Error?e.message:'骨格を読み取れませんでした。');}finally{if(id===poseRequest.current)setPoseBusy(false);}}
 const showPose=overlay&&poses&&!s.playing&&!s.camera&&Math.abs(s.time-poses.times[0])<.06&&Math.abs(s.selfTime-poses.times[1])<.06;
 function resetAlignment(){setPoses(null);s.setAlignment({x:0,y:0,scale:1,rotation:0,opacity:.5,perspectiveX:0,perspectiveY:0});}
 const fileInput=(i:number,label:string)=><label className="button file-button"><Upload size={17}/>{label}<input type="file" accept="video/*,.mov,.mp4,.webm" disabled={s.recording} aria-label={`${i===0?'お手本':'自分'}の動画を選ぶ`} onChange={e=>{const f=e.target.files?.[0];if(f)s.loadFile(i,f);e.target.value='';}}/></label>;
 const recentPicker=(i:number)=><RecentMediaPicker index={i} loadFile={file=>s.loadFile(i,file)} loadLink={saveLink} disabled={s.recording} pause={s.pause}/>;
 const silentTapNotice=config!==null&&step==='tempo'&&/^(TAP:|毎拍)/.test(s.notice);
 return <main className={'studio '+(config!==null?'editing ':'')+(isYoutube?'has-youtube ':'')+(panel==='alignment'?'aligning':'')}>
  <header className="masthead"><div className="brand">{config!==null?<button className="icon-button" aria-label="練習画面に戻る" onClick={()=>closeConfig()}><ArrowLeft/></button>:<Activity className="brandmark"/>}<h1>{config!==null?`${config===0?'お手本':'自分'}の設定`:'ヲタ芸マスター'}</h1></div>{config===null?<Tabs value={mode} onValueChange={v=>{if(v==='overlay'&&isYoutube){s.setNotice('YouTubeは比較モードで使えます。重ね合わせには動画ファイルを選んでください。');return;}if(v==='compare')setPanel(null);setMode(String(v));}}><TabsList aria-label="動画の表示"><TabsTrigger value="compare"><Columns2/><span>比較</span></TabsTrigger><TabsTrigger value="overlay"><Layers2/><span>重ねる</span></TabsTrigger></TabsList></Tabs>:<span className="private-label">動画ごとに設定</span>}</header>
  <div className={'decks '+(overlay?'overlaid ':'')+(config!==null?'configuring':'')}>
   {[0,1].map(i=>{
    const source=s.sources[i],yt=i===0&&!!s.sources[0]?.youtube,live=i===1&&s.camera,selected=config===i,empty=!source&&!live,t=i===0?s.time:s.selfTime,available=!!source&&(yt?s.youtubeReady:s.durations[i]>0)&&!live; const cutSource=live?'camera':source?.url||'',cutKey=cutSource+'|'+backgrounds[i].mode,cutActive=!yt&&!empty&&backgrounds[i].mode!=='off'&&(config===null||selected),cutReady=cutActive&&backgroundReady[i]===cutKey; const mediaStyle={transform:i===1&&overlay?alignmentCss(s.alignment,stageSize,s.mirrors[i]):`scaleX(${s.mirrors[i]?-1:1})`,opacity:i===1&&overlay?s.alignment.opacity:1};
    return <section className={`deck deck-${i} ${selected?'selected':''} ${drag===i?'dragging':''}`} key={i} onDragOver={e=>{e.preventDefault();setDrag(i);}} onDragLeave={()=>setDrag(null)} onDrop={e=>{e.preventDefault();setDrag(null);if(s.recording)return;const f=e.dataTransfer.files[0];if(f)s.loadFile(i,f);}}>
     <header className="deck-header"><span className="deck-dot"/><strong>{i===0?'お手本':'自分'}</strong><span className="filename" title={source?.name}>{live?'インカメ':source?.name||'動画未選択'}</span><span className="deck-status">{live?'LIVE':i===1&&s.optimized?'軽量版':s.bpmKinds[i]==='unset'?'BPM 未設定':`${s.bpm[i]} BPM`}</span></header>
     <div className="deck-body"><div ref={i===1?selfStage:undefined} className={'video-stage '+(selected&&available&&!yt?'with-preview ':'')+(yt?'youtube-stage':'')+(cutReady&&!overlay?' cutout-preview '+backgrounds[i].preview:'')}>
      {yt&&source?.youtube?<YouTubeReference key={source.key+":"+source.instance} link={source.youtube} ready={s.attachYoutube} state={s.youtubeState} rate={s.youtubeRate} error={s.youtubeError} metadata={s.youtubeMetadata}/>:<video ref={i===0?s.reference:s.self} src={source?.url} playsInline muted={i===1} preload="auto" style={{...mediaStyle,opacity:cutReady?0:mediaStyle.opacity}} onLoadedMetadata={()=>{if(!live)s.loaded(i);}} onEnded={i===0?s.mediaEnded:()=>{if(s.soloPlaying===1)s.pause();}} onWaiting={i===0?s.mediaWaiting:()=>s.interruptTap(i)} onSeeking={()=>s.interruptTap(i)} onPause={e=>{if(e.currentTarget.paused)s.interruptTap(i);}} onPlaying={i===0?s.mediaPlaying:undefined} onError={()=>{if(source&&!live)s.mediaError(i);}} aria-label={i===0?'お手本の映像':'自分の映像'}/>}
      {cutActive&&<BackgroundVideo video={i===0?s.reference:s.self} settings={backgrounds[i]} source={cutSource} active={cutActive} style={mediaStyle} status={(ready,message)=>{setBackgroundReady(v=>{const next=ready?cutKey:'';return v[i]===next?v:v.map((old,j)=>i===j?next:old);});if(message)s.setNotice(message);}}/>}
      {showPose&&poses&&<PoseOverlay stage={poses.stage} color={i===0?'#cdfa69':'#c5afff'} points={i===0?poses.points[0]:transformPose(poses.points[1],s.alignment,poses.stage)}/>}
      {empty&&<div className="empty-stage"><p>{i===0?'お手本の動画を選ぶ':'自分の動画、またはインカメ'}</p><div className="empty-actions">{fileInput(i,'動画を選ぶ')}{recentPicker(i)}{i===0&&<button className="button" onClick={()=>openConfig(0,'source')}>YouTubeリンク</button>}{i===1&&<button className="button" onClick={s.startCamera} disabled={s.cameraBusy}><Camera size={17}/>{s.cameraBusy?'起動中':'インカメ'}</button>}</div><small>動画は端末内で処理します</small></div>}
      {i===0&&!yt&&s.buffering&&<span className="stage-badge">読み込み中</span>}{live&&s.recording&&<span className="stage-badge rec">● REC</span>}
      {i===1&&source&&!live&&s.playing&&(targetSelf<0||targetSelf>=s.durations[1])&&<span className="stage-badge">{targetSelf<0?'動画の開始前':'動画の終了後'}</span>}
      {selected&&available&&!yt&&<div className="preview-tools"><Range label={`${i===0?'お手本':'自分'}の位置を調整`} value={t} max={s.durations[i]} onChange={v=>s.seekSolo(i,v)}/><div><button className="preview-nudge" onClick={()=>s.seekSolo(i,t-.1)} aria-label="0.1秒戻す"><ChevronLeft size={16}/><span>0.1秒</span></button><button className="preview-play" onClick={()=>s.soloPlaying===i?s.pause():void s.playSolo(i)} aria-label={s.soloPlaying===i?'この動画を一時停止':'この動画だけ等速で音付き再生'}>{s.soloPlaying===i?<Pause size={18}/>:<Play size={18}/>}<span>{s.soloPlaying===i?'停止':'等速再生'}</span></button><button className="preview-nudge" onClick={()=>s.seekSolo(i,t+.1)} aria-label="0.1秒進める"><span>0.1秒</span><ChevronRight size={16}/></button><span className="mono">{timeLabel(t)}</span></div></div>}
     </div><aside className="tool-rail" aria-label={`${i===0?'お手本':'自分'}の操作`}><button className={selected?'active':''} disabled={s.recording} onClick={()=>selected?closeConfig():openConfig(i)} aria-label={`${i===0?'お手本':'自分'}の設定`} aria-pressed={selected}><Settings2/><span>{selected?'戻る':'設定'}</span></button><button disabled={yt} title={yt?'YouTubeの反転はできません':undefined} onClick={()=>s.setMirrors(a=>a.map((v,j)=>i===j?!v:v))} aria-pressed={s.mirrors[i]}><FlipHorizontal2/><span>反転</span></button>{live?<button className={s.recording?'recording':''} onClick={s.toggleRecording} aria-label={s.recording?'録画停止':'録画開始'}>{s.recording?<Square/>:<span className="rec-dot"/>}<span>{s.recording?'停止':'録画'}</span></button>:<button disabled={s.recording} onClick={()=>openConfig(i,'source')}><Upload/><span>読込</span></button>}</aside></div>
     {selected&&<Tabs className="video-config" value={step} onValueChange={v=>changeStep(String(v))}><TabsList aria-label="動画設定の項目"><TabsTrigger value="tempo">拍・BPM</TabsTrigger><TabsTrigger value="origin">拍の位置</TabsTrigger><TabsTrigger value="display">表示</TabsTrigger><TabsTrigger value="source">動画</TabsTrigger></TabsList>
      <TabsContent value="origin" className="config-content"><h2>拍の位置を微調整</h2><p>拍タップで位置も設定済みです。ずれが残る場合は秒数を調整するか、動画の位置を選び直せます。</p>{yt&&<p className="config-hint">YouTube内の操作で再生・停止してください。頭出しはフレーム単位の精度ではありません。</p>}<button className="button primary wide" disabled={!available} onClick={()=>s.markOrigin(i)}><Check size={17}/>この位置を最初の「1」にする</button><div className="origin-value"><Numeric label="「1」の位置（秒）" value={s.origins[i]} max={s.durations[i]||999} step={.01} disabled={!available} onChange={v=>{s.pause();s.setOrigins(a=>a.map((n,j)=>i===j?v:n));}}/><button className="button" disabled={!available} onClick={()=>s.seekSolo(i,s.origins[i])}>「1」に戻る</button></div>{!available&&<span className="config-hint">{live?'インカメは曲に合わせて踊るので、起点設定は不要です。':'「動画」タブで先に動画を選んでください。'}</span>}</TabsContent>
      <TabsContent value="tempo" className="config-content tempo-content"><TempoConfig key={source?.key||i} remote={yt} file={s.files.current[i]} live={live} bpm={s.bpm[i]} kind={s.bpmKinds[i]} tapRecording={s.tapRecording===i} tapGrid={s.tapGrids[i]} beginTap={()=>void s.beginTap(i)} finishTap={s.finishTap} tapCount={s.tapCounts[i]} tap={()=>s.tap(i)} apply={(v,kind)=>s.applyBpm(i,v,kind)} pause={s.pause}/></TabsContent>
      <TabsContent value="display" className="config-content"><BackgroundControls settings={backgrounds[i]} change={v=>changeBackground(i,v)} disabled={yt||empty}/><h2>見やすい向きに合わせる</h2><label className="setting-row"><span>左右反転</span><Switch aria-label="この動画の左右反転" disabled={yt} checked={s.mirrors[i]} onCheckedChange={v=>s.setMirrors(a=>a.map((n,j)=>i===j?v:n))}/></label><p>{yt?'YouTubeは反転・重ね合わせ・骨格解析に対応していません。動画ファイルを選ぶと使えます。':i===0?'鏡のようにまねしたい場合は、お手本を反転します。':'インカメは初期状態で左右反転しています。'}</p>{i===1&&!isYoutube&&<button className="button" onClick={()=>{closeConfig();setMode('overlay');setPanel('alignment');}}><Layers2 size={17}/>重ねる位置・倍率を調整</button>}<div className="config-hint">同期時の速度：{live?'ライブ':missingBpm!==null?'BPM設定後に表示':`${(i===0?s.rate:selfRate).toFixed(2)}倍`}</div></TabsContent>
      <TabsContent value="source" className="config-content source-content"><h2>{i===0?'お手本にする動画':'自分の映像を選ぶ'}</h2><div className="source-actions">{fileInput(i,'動画ファイル')}{recentPicker(i)}{i===1&&<button className="button" onClick={live?s.stopCamera:s.startCamera} disabled={s.cameraBusy}><Camera size={17}/>{live?'カメラ停止':s.cameraBusy?'起動中':'インカメ'}</button>}{i===1&&s.recordingDownload&&<a className="button" href={s.recordingDownload.url} download={s.recordingDownload.name}><Download size={17}/>録画を保存</a>}</div>{i===0?<><form className="link-form" onSubmit={e=>{e.preventDefault();saveLink();}}><input type="url" value={link} onChange={e=>setLink(e.target.value)} placeholder="YouTubeの共有リンクを貼る" aria-label="YouTubeの動画リンク" required/><button className="button primary" type="submit">読み込む</button></form><p className="config-hint">YouTubeはここで再生。通常の動画・Shorts・共有リンクに対応。Xは参考リンクの保存のみ。</p>{savedLink&&<><button className="button" onClick={()=>saveLink(savedLink)}>前回のリンクを読み込む</button><a className="saved-link" href={savedLink} target="_blank" rel="noopener noreferrer"><ExternalLink size={14}/>元サイトで開く</a></>}</>:<><p>インカメは動画横の「録画」で撮影できます。</p>{source&&!live&&<><div className="source-actions"><button className="button" disabled={s.optimizing||s.optimized} onClick={()=>void s.makeLightVideo()}>{s.optimizing?`軽量化 ${Math.round(s.optimizeProgress*100)}%`:s.optimized?'軽量版を使用中':'カクつく動画を軽量化'}</button>{s.optimizing&&<button className="button" onClick={s.cancelOptimization}>中止</button>}{s.optimized&&<button className="button" onClick={s.useOriginalVideo}>元の動画に戻す</button>}</div><p className="config-hint">端末内で長辺720px・30fpsのMP4を作ります。軽量版は音声なし。時間軸・BPM設定は維持します。</p></>}</>}</TabsContent>
     </Tabs>}
    </section>;
   })}
  </div>
  {config===null&&panel==='alignment'?<AlignmentEditor background={<BackgroundControls settings={backgrounds[1]} change={v=>changeBackground(1,v)} disabled={!s.sources[1]&&!s.camera}/>} alignment={s.alignment} change={(key,value)=>{s.pause();s.setAlignment(a=>({...a,[key]:value}));}} auto={()=>void autoAlign()} busy={poseBusy} disabled={s.optimizing||!s.sources[0]||(!s.sources[1]&&!s.camera)} close={()=>setPanel(null)} reset={resetAlignment} form={poses? <div className="form-differences"><small style={{gridColumn:"1/-1"}}>位置合わせ時のフォーム差（2D）</small>{[[11,13,15],[12,14,16],[23,25,27],[24,26,28]].map((ids,j)=>{const a=jointAngle(poses.points[0],ids[0],ids[1],ids[2]);const counterpart=poses.mirrors[0]!==poses.mirrors[1]?ids.map(n=>n%2?n+1:n-1):ids;const b=jointAngle(poses.points[1],counterpart[0],counterpart[1],counterpart[2]);return <span key={j}>{['左肘','右肘','左膝','右膝'][j]}の角度差 {a===null||b===null?'未検出':`${Math.round(Math.abs(a-b))}°`}</span>;})}</div>:<p>同じ姿勢で止めて、下の骨格合わせを実行してください。</p>}/>:config===null?<footer className="practice-dock"><div className="count-row"><span className="phrase-label">{counted&&beat.phrase>0?`${beat.phrase}エイト目`:'8カウント'}</span><div className="beat-cells" aria-label="現在の拍">{[1,2,3,4,5,6,7,8].map(n=><span key={n} className={counted&&beat.phrase>0&&beat.beat===n?'active':''}>{n}</span>)}</div><label className="click-toggle"><span>拍音</span><Switch size="sm" disabled={!counted} checked={s.click} onCheckedChange={s.setClick} aria-label="拍のクリック音"/></label></div>
   {!isYoutube&&<VideoTracks durations={s.durations} origins={s.origins} bpm={s.bpm} known={s.bpmKinds.map(k=>k!=='unset')} time={s.time} playing={s.playing} camera={s.camera} disabled={s.recording||poseBusy||s.optimizing} seek={s.seek} adjust={s.adjustOrigin} pause={s.pause} save={s.saveSettings}/>}
   <div className="transport"><button className="transport-option" disabled={s.recording} onClick={()=>{if(isYoutube)s.pause();setPanel('speed');}} aria-label="練習速度を設定"><strong>{s.rate.toFixed(2)}×</strong><span>速度</span></button><button className="icon-button" disabled={!counted||s.recording} onClick={()=>s.seek(s.time-60/s.bpm[0])} aria-label="1拍戻す"><SkipBack/></button><button className="play-button" disabled={!hasReference||(missingBpm===null&&invalidRate)||poseBusy||s.optimizing} onClick={()=>s.playing?s.pause():missingBpm!==null?openConfig(missingBpm,'tempo'):void s.play()}>{s.playing?<Pause size={20}/>:<Play size={20}/>}<span>{s.playing?'停止':missingBpm!==null?'BPMを設定':'同期再生'}</span></button><button className="icon-button" disabled={!counted||s.recording} onClick={()=>s.seek(s.time+60/s.bpm[0])} aria-label="1拍進める"><SkipForward/></button><button className={'transport-option '+(s.loop.enabled?'on':'')} disabled={!counted||s.recording} onClick={()=>{if(isYoutube)s.pause();setPanel('loop');}} aria-label="区間ループを設定"><Repeat2 size={20}/><span>ループ</span></button>{isYoutube&&<button className="transport-option" onClick={()=>{s.pause();setPanel('tracks');}}><SlidersHorizontal size={20}/><span>トラック</span></button>}{overlay&&<button className="transport-option" onClick={()=>{s.pause();setPanel('alignment');}} aria-label="重ね合わせ調整"><SlidersHorizontal size={20}/><span>位置</span></button>}</div>
  </footer>:<footer className="config-dock"><button className="button" onClick={()=>step==='origin'?changeStep('tempo'):changeStep('origin')}>{step==='origin'?'拍・BPMへ':'拍の位置を微調整'}<ChevronRight size={16}/></button><button className="button primary" onClick={()=>closeConfig(true)}><Check size={17}/>保存して戻る</button></footer>}
  {s.notice&&!silentTapNotice&&<div className="notice" role="status"><span>{s.notice}</span><button className="icon-button" onClick={()=>s.setNotice('')} aria-label="メッセージを閉じる"><X size={16}/></button></div>}
  <Dialog open={panel!==null&&panel!=='alignment'} onOpenChange={open=>{if(!open)setPanel(null);}}><DialogContent className="practice-dialog"><DialogTitle>{panel==='speed'?'練習速度':panel==='loop'?'区間ループ':panel==='tracks'?'2本のタイミング調整':'重ね合わせ調整'}</DialogTitle><DialogDescription>{panel==='speed'?'両方の動画を同じ拍の速さに合わせます。':panel==='loop'?'今いるエイトから、選んだ長さを繰り返します。':panel==='tracks'?'上下のトラックを動かして、最初の「1」を合わせます。YouTubeの頭出しには誤差があります。':'骨格を使って合わせ、必要に応じて手動で調整します。'}</DialogDescription>
   {panel==='tracks'&&<VideoTracks durations={s.durations} origins={s.origins} bpm={s.bpm} known={s.bpmKinds.map(k=>k!=='unset')} time={s.time} playing={s.playing} camera={s.camera} disabled={s.recording||poseBusy||s.optimizing} seek={s.seek} adjust={s.adjustOrigin} pause={s.pause} save={s.saveSettings}/>}
   {panel==='speed'&&<><label className="setting-row"><span>滑らかさ優先</span><Switch checked={s.smooth} onCheckedChange={s.setSmooth} aria-label="再生中の自動補正を抑える"/></label><p className="config-hint">ONではBPMの比率による一定速度で再生します。ずれたら再同期してください。</p><div className="playback-status"><span>自分の動画 {selfRate.toFixed(2)}倍 / ずれ {Math.abs(s.drift).toFixed(2)}秒</span>{s.quality&&<span>デコード {s.quality.fps} fps / コマ落ち {s.quality.dropped}</span>}</div><button className="button" disabled={!hasReference||s.optimizing} onClick={()=>{s.seek(s.time);s.setNotice('今の位置で動画を合わせ直しました。');}}>今の位置で再同期</button><div className="speed-readout"><strong>{s.rate.toFixed(2)}×</strong><span>{counted?`${(s.bpm[0]*s.rate).toFixed(1)} BPM`:'BPM 未設定'}</span></div>{!isYoutube&&<Range label="練習速度" min={.25} max={2} step={.05} value={s.rate} onChange={s.setRate}/>}{isYoutube&&<p className="config-hint">YouTubeが対応する速度から選びます。速度変更時は一時停止します。</p>}<div className="speed-presets">{(isYoutube?s.youtubeRates.filter(n=>n>=.25&&n<=2):[.5,.75,1,1.25]).map(n=><button className={'button '+(s.rate===n?'chosen':'')} key={n} onClick={()=>s.setRate(n)}>{n}×</button>)}</div></>}
   {panel==='loop'&&<><label className="setting-row"><span>ループする</span><Switch aria-label="区間ループ" checked={s.loop.enabled} onCheckedChange={v=>{if(v&&s.loop.end-s.loop.start<.1)setLoopFromPhrase(phrases);else s.setLoop(l=>({...l,enabled:v}));}}/></label><div className="speed-presets">{[1,2,4].map(n=><button className={'button '+(phrases===n&&s.loop.enabled?'chosen':'')} key={n} onClick={()=>setLoopFromPhrase(n)}>{n}エイト</button>)}</div><div className="loop-points"><Numeric label="A 始点（秒）" value={s.loop.start} max={Math.max(0,s.loop.end-.1)} step={.01} onChange={n=>s.setLoop(l=>({...l,start:n}))}/><Numeric label="B 終点（秒）" value={s.loop.end} min={s.loop.start+.1} max={Math.max(s.loop.start+.1,s.durations[0])} step={.01} onChange={n=>s.setLoop(l=>({...l,end:n}))}/></div><div className="speed-presets"><button className="button" onClick={()=>{const start=clamp(s.time,0,Math.max(0,s.durations[0]-.1));s.setLoop(l=>({...l,start,end:Math.min(s.durations[0],Math.max(l.end,start+480/s.bpm[0]))}));}}>今をAにする</button><button className="button" disabled={s.time<=s.loop.start+.1} onClick={()=>s.setLoop(l=>({...l,end:s.time}))}>今をBにする</button></div></>}

   <button className="button primary wide" onClick={()=>setPanel(null)}>完了</button>
  </DialogContent></Dialog>
 </main>;
}

